### ISSUE TITLE
Unresolved external symbols

### ISSUE THREAD

**Issue by lordsaibat** [hatRiot/token-priv#2] opened 2017-09-01 19:06 UTC
![image](https://user-images.githubusercontent.com/6404932/29984128-fb317ba4-8f26-11e7-8e24-a513e263a472.png)

Seems to be several unresolved external symbols not resolving.

**Comment by hatRiot** [comment] 2017-09-05 16:55
Looks like we missed some library references.  I'll take a look later this evening and ensure it's building properly.

**Comment by hatRiot** [comment] 2017-09-20 03:45
I'm actually not able to reproduce this, even after checking out straight from the repository.  It looks like you might be missing a linker reference to MSFRottenPotato.lib, which is included in this repository.

I do want to stress that it probably won't compile even after that; the project is an amalgam of different snippets of code and not meant to be a toolkit, but rather serve as a reference for the techniques and strategies used in our token research.  If there's interest, we'll look into cleaning it all up into something more akin to a toolkit.

**Comment by lordsaibat** [comment] 2017-09-20 16:13
I am working on a Masters paper, I wanted to demonstrate the privileges and
the risk involved with having them on users. If there is a way to separate
those function into stand alone exe? I am not great at coding.

Currently my only example is mimikatz and how it use sedebug,
seimpersonate, and setcb.

**Comment by hatRiot** [comment] 2017-09-20 16:22
If you check the repository code, each privilege has been separated into its own function(s), so you can easily copy it out and add it to your own code.  For example, here's [SeRestorePrivilege](https://raw.githubusercontent.com/hatRiot/token-priv/master/poptoke/poptoke/SeRestorePrivilege.cpp), and here's [SeTakeOwnershipPrivilege](https://raw.githubusercontent.com/hatRiot/token-priv/master/poptoke/poptoke/SeTakeOwnershipPrivilege.cpp).

If you'd like help with usage/implementation, please email me at bryan.j.alexander AT protonmail DOT com and I can further assist you.  Closing this issue out, otherwise.

**Closed as completed by hatRiot** 2017-09-20 16:22 UTC
